[package]
name = "submerge-crystal"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
actix-web = { workspace = true }
anyhow = { workspace = true }
async-trait = { workspace = true }
clap = { workspace = true }
frame-metadata = { workspace = true }
frame-system = { workspace = true }
futures-util = { workspace = true }
hex = { workspace = true }
lazy_static = { workspace = true }
log = { workspace = true }
once_cell = { workspace = true }
parity-scale-codec = { workspace = true }
rustc-hash = { workspace = true }
serde_json = { workspace = true }
sp-runtime = { workspace = true }
sqlx = { workspace = true }
submerge-base = { path = "../submerge-base" }
submerge-metrics = { path = "../submerge-metrics" }
submerge-persistence = { path = "../submerge-persistence" }
submerge-substrate-client = { path = "../submerge-substrate-client" }
submerge-util = { path = "../submerge-util" }
tokio = { workspace = true }
scale-info = { workspace = true }
serde = { workspace = true }

[dev-dependencies]
log = { workspace = true }
serde_json = { workspace = true }
test-log = { workspace = true }
