[substrate]
chain = "polkadot"
chain_display = "Polkadot"
chain_genesis_hash = "0x91B171BB158E2D3848FA23A9F1C25182FB8E20313B2C1EB49219DA7A70CE90C3"
ss58_prefix = 0
rpc_url = "wss://rpc.helikon.io/polkadot"
token_ticker = "DOT"
token_decimals = 10