[substrate]
chain = "westend"
chain_display = "Westend"
chain_genesis_hash = "0xe143f23803ac50e8f6f8e62695d1ce9e4e1d68aa36c1cd2cfd15340213f3423e"
ss58_prefix = 42
rpc_url = "wss://rpc.helikon.io/westend"
token_ticker = "WND"
token_decimals = 12