[substrate]
chain = "westend"
chain_display = "Westend"
chain_genesis_hash = "0xE143F23803AC50E8F6F8E62695D1CE9E4E1D68AA36C1CD2CFD15340213F3423E"
ss58_prefix = 42
rpc_url = "wss://rpc.helikon.io/westend"
token_ticker = "WND"
token_decimals = 12