[package]
name = "submerge-persistence"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
anyhow = { workspace = true }
sqlx = { workspace = true }
submerge-base = { path = "../submerge-base" }
tracing = { workspace = true }