// This file is auto-generated by @hey-api/openapi-ts

import type {
    GetBlocksByReferenceResponse,
    GetBlocksResponse,
    GetCallByHashResponse,
    GetCallExtrinsicByHashResponse,
    GetCallsByBlockReferenceAndExtrinsicIndexResponse,
    GetCallsByBlockReferenceResponse,
    GetCallsByExtrinsicHashResponse,
    GetCallsResponse,
    GetEventByHashResponse,
    GetEventsByBlockReferenceAndExtrinsicIndexResponse,
    GetEventsByBlockReferenceAndIndexResponse,
    GetEventsByBlockReferenceResponse,
    GetEventsByExtrinsicHashResponse,
    GetEventsResponse,
    GetExtrinsicByHashResponse,
    GetExtrinsicRootCallByHashResponse,
    GetExtrinsicsByBlockReferenceAndIndexResponse,
    GetExtrinsicsByBlockReferenceResponse,
    GetExtrinsicsResponse,
    GetGenesisRecordsResponse,
    GetMetadataListResponse,
    GetParentCallByHashResponse,
    GetSubCallsByHashResponse,
    GetTraceByHashResponse,
    GetTracesByBlockReferenceResponse,
    GetTracesResponse,
} from './types.gen';

const blockSchemaResponseTransformer = (data: any) => {
    data.number = BigInt(data.number.toString());
    if (data.timestamp) {
        data.timestamp = BigInt(data.timestamp.toString());
    }
    return data;
};

export const getBlocksResponseTransformer = async (data: any): Promise<GetBlocksResponse> => {
    data.data = data.data.map((item: any) => blockSchemaResponseTransformer(item));
    return data;
};

export const getBlocksByReferenceResponseTransformer = async (
    data: any,
): Promise<GetBlocksByReferenceResponse> => {
    data = data.map((item: any) => blockSchemaResponseTransformer(item));
    return data;
};

const callSchemaResponseTransformer = (data: any) => {
    data.blockNumber = BigInt(data.blockNumber.toString());
    if (data.blockTimestamp) {
        data.blockTimestamp = BigInt(data.blockTimestamp.toString());
    }
    return data;
};

const paginationDataSchemaResponseTransformer = (data: any) => {
    data.total = BigInt(data.total.toString());
    return data;
};

export const getCallsByBlockReferenceResponseTransformer = async (
    data: any,
): Promise<GetCallsByBlockReferenceResponse> => {
    data.data = data.data.map((item: any) => callSchemaResponseTransformer(item));
    data.pagination = paginationDataSchemaResponseTransformer(data.pagination);
    return data;
};

const eventSchemaResponseTransformer = (data: any) => {
    data.blockNumber = BigInt(data.blockNumber.toString());
    if (data.blockTimestamp) {
        data.blockTimestamp = BigInt(data.blockTimestamp.toString());
    }
    return data;
};

export const getEventsByBlockReferenceResponseTransformer = async (
    data: any,
): Promise<GetEventsByBlockReferenceResponse> => {
    data.data = data.data.map((item: any) => eventSchemaResponseTransformer(item));
    data.pagination = paginationDataSchemaResponseTransformer(data.pagination);
    return data;
};

export const getEventsByBlockReferenceAndIndexResponseTransformer = async (
    data: any,
): Promise<GetEventsByBlockReferenceAndIndexResponse> => {
    data = data.map((item: any) => eventSchemaResponseTransformer(item));
    return data;
};

const extrinsicSchemaResponseTransformer = (data: any) => {
    data.blockNumber = BigInt(data.blockNumber.toString());
    if (data.blockTimestamp) {
        data.blockTimestamp = BigInt(data.blockTimestamp.toString());
    }
    return data;
};

export const getExtrinsicsByBlockReferenceResponseTransformer = async (
    data: any,
): Promise<GetExtrinsicsByBlockReferenceResponse> => {
    data.data = data.data.map((item: any) => extrinsicSchemaResponseTransformer(item));
    data.pagination = paginationDataSchemaResponseTransformer(data.pagination);
    return data;
};

export const getExtrinsicsByBlockReferenceAndIndexResponseTransformer = async (
    data: any,
): Promise<GetExtrinsicsByBlockReferenceAndIndexResponse> => {
    data = data.map((item: any) => extrinsicSchemaResponseTransformer(item));
    return data;
};

export const getCallsByBlockReferenceAndExtrinsicIndexResponseTransformer = async (
    data: any,
): Promise<GetCallsByBlockReferenceAndExtrinsicIndexResponse> => {
    data.data = data.data.map((item: any) => callSchemaResponseTransformer(item));
    data.pagination = paginationDataSchemaResponseTransformer(data.pagination);
    return data;
};

export const getEventsByBlockReferenceAndExtrinsicIndexResponseTransformer = async (
    data: any,
): Promise<GetEventsByBlockReferenceAndExtrinsicIndexResponse> => {
    data.data = data.data.map((item: any) => eventSchemaResponseTransformer(item));
    data.pagination = paginationDataSchemaResponseTransformer(data.pagination);
    return data;
};

const traceSchemaResponseTransformer = (data: any) => {
    data.blockNumber = BigInt(data.blockNumber.toString());
    return data;
};

export const getTracesByBlockReferenceResponseTransformer = async (
    data: any,
): Promise<GetTracesByBlockReferenceResponse> => {
    data.data = data.data.map((item: any) => traceSchemaResponseTransformer(item));
    data.pagination = paginationDataSchemaResponseTransformer(data.pagination);
    return data;
};

export const getCallsResponseTransformer = async (data: any): Promise<GetCallsResponse> => {
    data.data = data.data.map((item: any) => callSchemaResponseTransformer(item));
    return data;
};

export const getCallByHashResponseTransformer = async (
    data: any,
): Promise<GetCallByHashResponse> => {
    data = callSchemaResponseTransformer(data);
    return data;
};

export const getCallExtrinsicByHashResponseTransformer = async (
    data: any,
): Promise<GetCallExtrinsicByHashResponse> => {
    data = extrinsicSchemaResponseTransformer(data);
    return data;
};

export const getParentCallByHashResponseTransformer = async (
    data: any,
): Promise<GetParentCallByHashResponse> => {
    data = callSchemaResponseTransformer(data);
    return data;
};

export const getSubCallsByHashResponseTransformer = async (
    data: any,
): Promise<GetSubCallsByHashResponse> => {
    data.data = data.data.map((item: any) => callSchemaResponseTransformer(item));
    data.pagination = paginationDataSchemaResponseTransformer(data.pagination);
    return data;
};

export const getEventsResponseTransformer = async (data: any): Promise<GetEventsResponse> => {
    data.data = data.data.map((item: any) => eventSchemaResponseTransformer(item));
    return data;
};

export const getEventByHashResponseTransformer = async (
    data: any,
): Promise<GetEventByHashResponse> => {
    data = eventSchemaResponseTransformer(data);
    return data;
};

export const getExtrinsicsResponseTransformer = async (
    data: any,
): Promise<GetExtrinsicsResponse> => {
    data.data = data.data.map((item: any) => extrinsicSchemaResponseTransformer(item));
    return data;
};

export const getExtrinsicByHashResponseTransformer = async (
    data: any,
): Promise<GetExtrinsicByHashResponse> => {
    data = extrinsicSchemaResponseTransformer(data);
    return data;
};

export const getExtrinsicRootCallByHashResponseTransformer = async (
    data: any,
): Promise<GetExtrinsicRootCallByHashResponse> => {
    data = callSchemaResponseTransformer(data);
    return data;
};

export const getCallsByExtrinsicHashResponseTransformer = async (
    data: any,
): Promise<GetCallsByExtrinsicHashResponse> => {
    data.data = data.data.map((item: any) => callSchemaResponseTransformer(item));
    data.pagination = paginationDataSchemaResponseTransformer(data.pagination);
    return data;
};

export const getEventsByExtrinsicHashResponseTransformer = async (
    data: any,
): Promise<GetEventsByExtrinsicHashResponse> => {
    data.data = data.data.map((item: any) => eventSchemaResponseTransformer(item));
    data.pagination = paginationDataSchemaResponseTransformer(data.pagination);
    return data;
};

export const getGenesisRecordsResponseTransformer = async (
    data: any,
): Promise<GetGenesisRecordsResponse> => {
    data.pagination = paginationDataSchemaResponseTransformer(data.pagination);
    return data;
};

export const getMetadataListResponseTransformer = async (
    data: any,
): Promise<GetMetadataListResponse> => {
    data.pagination = paginationDataSchemaResponseTransformer(data.pagination);
    return data;
};

export const getTracesResponseTransformer = async (data: any): Promise<GetTracesResponse> => {
    data.data = data.data.map((item: any) => traceSchemaResponseTransformer(item));
    return data;
};

export const getTraceByHashResponseTransformer = async (
    data: any,
): Promise<GetTraceByHashResponse> => {
    data = traceSchemaResponseTransformer(data);
    return data;
};
