import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

function headerifyTopCategories(items: [any]) {
    return items.map((item) => {
        if (item.type === 'category') {
            // remove link & collapse behaviour
            const { link, ...rest } = item;
            return {
                ...rest,
                collapsible: false,
                collapsed: false, // has no effect if collapsible is false
                items: headerifyTopCategories(item.items),
            };
        }
        return item;
    });
}

const crystalAPISidebar = require('./docs/crystal-api/sidebar.ts');

const sidebars: SidebarsConfig = {
    tutorialSidebar: [
        {
            type: 'doc',
            id: 'introduction',
            label: 'Introduction',
        },
        {
            type: 'category',
            label: 'Basics',
            collapsible: false,
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'tutorial-basics',
                },
            ],
        },
        {
            type: 'category',
            label: 'Extras',
            collapsible: false,
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'tutorial-extras',
                },
            ],
        },
    ],
    crystalAPISidebar: headerifyTopCategories(crystalAPISidebar),
};

export default sidebars;
