[package]
name = "dv-report-metadata"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true

[features]
kusama = []
polkadot = []

[dependencies]
parity-scale-codec = { workspace = true }
subxt = { workspace = true }
dv-report-types = { path = "../dv-report-types" }