[package]
name = "dv-report-api-service"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
actix-web = { workspace = true }
actix-cors = { workspace = true }
anyhow = { workspace = true }
async-trait = { workspace = true }
dv-report-config = { path = "../dv-report-config" }
dv-report-logging = { path = "../dv-report-logging" }
dv-report-metrics = { path = "../dv-report-metrics" }
dv-report-persistence = { path = "../dv-report-persistence" }
dv-report-service = { path = "../dv-report-service" }
dv-report-types = { path = "../dv-report-types" }
futures-util = { workspace = true }
log = { workspace = true }
moka = { workspace = true }
once_cell = { workspace = true }
tokio = { workspace = true, features = ["full"] }
serde = { workspace = true, features = ["derive"] }