import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
    tutorialSidebar: [
        'introduction',
        { type: 'autogenerated', dirName: 'tutorial-basic' },
        { type: 'autogenerated', dirName: 'tutorial-extras' },
    ],
    openApiSidebar: [
        {
            type: 'category',
            label: 'Petstore',
            link: {
                type: 'generated-index',
                title: 'Petstore API',
                description:
                    'This is a sample server Petstore server. You can find out more about Swagger at http://swagger.io or on irc.freenode.net, #swagger. For this sample, you can use the api key special-key to test the authorization filters.',
                slug: '/petstore-api',
            },
            items: require('./docs/petstore-api/sidebar.js'),
        },
    ],
    placeholderApiSidebar: [
        {
            type: 'category',
            label: 'Placeholder',
            link: {
                type: 'generated-index',
                title: 'Placeholder API',
                description: 'A dummy API.',
                slug: '/placeholder-api',
            },
            items: require('./docs/placeholder-api/sidebar.js'),
        },
    ],
};

export default sidebars;
