services:
  submerge_crystal_postgres:
    networks:
      - submerge_crystal
    image: postgres:${POSTGRES_VERSION}
    restart: unless-stopped
    volumes:
      - submerge_crystal_postgres_data:/var/lib/postgresql
    ports:
      - ${CRYSTAL_POSTGRES_PORT}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_USER}
      POSTGRES_DB: ${CRYSTAL_POSTGRES_DB}
    # tuning parameters @ https://pgtune.leopard.in.ua/
    command: |
      postgres -c max_connections=32
               -c shared_buffers=2GB
               -c effective_cache_size=6GB
               -c maintenance_work_mem=512MB
               -c checkpoint_completion_target=0.9
               -c wal_buffers=16MB
               -c default_statistics_target=100
               -c random_page_cost=1.1
               -c effective_io_concurrency=200
               -c work_mem=52428kB
               -c huge_pages=off
               -c min_wal_size=1GB
               -c max_wal_size=2GB
volumes:
  submerge_crystal_postgres_data:
    external: false
networks:
  submerge_crystal:
    driver: bridge