[package]
name = "dv-report-repository"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true

[features]
kusama = ["dv-report-substrate-client/kusama"]
polkadot = ["dv-report-substrate-client/polkadot"]

[dependencies]
anyhow = { workspace = true }
async-recursion = { workspace = true }
dv-report-config = { path = "../dv-report-config" }
dv-report-persistence = { path = "../dv-report-persistence" }
dv-report-substrate-client = { path = "../dv-report-substrate-client" }
dv-report-subsquare-client = { path = "../dv-report-subsquare-client" }
dv-report-types= { path = "../dv-report-types" }
log = { workspace = true }