[package]
name = "submerge-sentinel"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true

[features]
integration-test = []

[dependencies]
anyhow = { workspace = true }
chrono = { workspace = true }
clap = { workspace = true }
reqwest = { workspace = true}
serde = { workspace = true }
serde_json = { workspace = true }
serde_repr = { workspace = true }
submerge-util = { path = "../submerge-util" }
tracing = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
tokio = { workspace = true }