[package]
name = "submerge-cli"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true

[[bin]]
name = "submerge"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
submerge-base = { path = "../submerge-base" }
submerge-crystal = { path = "../submerge-crystal" }
tokio = { workspace = true }