[common]
recovery_retry_seconds = 5

[log]
dv_report_level = "debug"
other_level = "warn"

[http]
request_timeout_seconds = 20

[postgres]
host = "127.0.0.1"
port = 5432
username = "dv_report"
password = "dv_report"
database_name = "dv_report"
pool_max_connections = 64
connection_timeout_seconds = 5

[substrate]
network_id = 1
chain = "polkadot"
chain_display = "Polkadot"
rpc_url = "wss://rpc.helikon.io:443/polkadot"
people_rpc_url = "wss://rpc.helikon.io:443/people-polkadot"
sidecar_url = "https://sidecar.helikon.io/polkadot"
connection_timeout_seconds = 15
request_timeout_seconds = 15
token_ticker = "DOT"
token_decimals = 10
token_format_decimal_points = 4

[api]
request_timeout_seconds = 60
service_host = "0.0.0.0"
api_service_port = 7900

[indexer]
cohort_number = 5
# optional - will be used the current runtime metadata if left blank
# metadata_file_path = "/path/to/metadata/file.scale"
# optional - the indexer uses the finalized block if left blank
# end_block_number = 0

[metrics]
host = "127.0.0.1"
api_service_port = 13005
indexer_port = 13000