//!
//! AUTO-GENERATED CODE - DO NOT EDIT!
//!
//! Submerge Crystal API v1
//! Source: api-spec/submerge-crystal-api.json
//! Version: 1.0.0
//! Generated by `oas3-gen v0.23.6`
//!
//! REST API for Submerge Crystal, the core indexer component of Submerge.
//! 
//! Submerge API endpoints are grouped under five resource sets:
//! - Blocks
//! - Calls
//! - Events
//! - Extrinsics
//! - Genesis
//! - Metadata
//! - Traces
//! - System
//! 
//! Public API is limited by 5 requests per second.
//! Request query parameters use `snake_case`; response fields use `camelCase`.

use anyhow::Context;
use reqwest::{Client, Url};
use validator::Validate;
use super::types::*;
pub const BASE_URL: &str = "https://coretime-polkadot.crystal.submerge.io/api/v1";
#[derive(Debug, Clone)]
pub struct SubmergeCrystalApiV1Client {
    pub client: Client,
    pub base_url: Url,
}
impl Default for SubmergeCrystalApiV1Client {
    fn default() -> Self {
        Self::new()
    }
}
impl SubmergeCrystalApiV1Client {
    /// Create a client using the OpenAPI `servers[0]` URL.
    #[must_use]
    #[track_caller]
    pub fn new() -> Self {
        Self {
            client: Client::builder().build().expect("client"),
            base_url: Url::parse(BASE_URL).expect("valid base url"),
        }
    }
    /// Create a client with a custom base URL.
    pub fn with_base_url(base_url: impl AsRef<str>) -> anyhow::Result<Self> {
        Ok(Self {
            client: Client::builder().build().context("building reqwest client")?,
            base_url: Url::parse(base_url.as_ref()).context("parsing base url")?,
        })
    }
    /// Create a client from an existing `reqwest::Client`.
    pub fn with_client(
        base_url: impl AsRef<str>,
        client: Client,
    ) -> anyhow::Result<Self> {
        let url = Url::parse(base_url.as_ref()).context("parsing base url")?;
        Ok(Self { client, base_url: url })
    }
    ///Get blocks
    ///
    ///Returns all blocks from the database that satisfy the query parameters. It will return a paginated response, ordered descending by block number.
    ///
    ///GET /blocks
    pub async fn blocks(
        &self,
        request: BlocksRequest,
    ) -> anyhow::Result<BlocksResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("blocks");
        let response = self.client.get(url).query(&request.query).send().await?;
        Ok(BlocksRequest::parse_response(response).await?)
    }
    ///Get blocks by reference
    ///
    ///If a hash is passed, returns the matching block. If a number is passed, gives the blocks by that number - could be multiple blocks if there's a pruned block in that slot.
    ///
    ///GET /blocks/{block_ref}
    pub async fn blocks_by_reference(
        &self,
        request: BlocksByReferenceRequest,
    ) -> anyhow::Result<BlocksByReferenceResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("blocks")
            .push(&request.path.block_ref.to_string());
        let response = self.client.get(url).send().await?;
        Ok(BlocksByReferenceRequest::parse_response(response).await?)
    }
    ///Get block calls
    ///
    ///If a hash is passed, returns the calls for the matching block. If a number is passed, gives the calls for the blocks with that number - could be multiple blocks if there's a pruned block in that slot.
    ///
    ///GET /blocks/{block_ref}/calls
    pub async fn calls_by_block_reference(
        &self,
        request: CallsByBlockReferenceRequest,
    ) -> anyhow::Result<SubCallsByHashResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("blocks")
            .push(&request.path.block_ref.to_string())
            .push("calls");
        let response = self.client.get(url).query(&request.query).send().await?;
        Ok(CallsByBlockReferenceRequest::parse_response(response).await?)
    }
    ///Get block events
    ///
    ///If a hash is passed, returns the events for the matching block. If a number is passed, gives the events for the block with that number - could be multiple blocks if there's a pruned block in that slot.
    ///
    ///GET /blocks/{block_ref}/events
    pub async fn events_by_block_reference(
        &self,
        request: EventsByBlockReferenceRequest,
    ) -> anyhow::Result<EventsByExtrinsicHashResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("blocks")
            .push(&request.path.block_ref.to_string())
            .push("events");
        let response = self.client.get(url).query(&request.query).send().await?;
        Ok(EventsByBlockReferenceRequest::parse_response(response).await?)
    }
    ///Get block events by index
    ///
    ///Returns the events in the given block at the given index. It can return multiple events if a number is passed and there's a pruned block in that slot.
    ///
    ///GET /blocks/{block_ref}/events/{event_index}
    pub async fn events_by_block_reference_and_index(
        &self,
        request: EventsByBlockReferenceAndIndexRequest,
    ) -> anyhow::Result<EventsByBlockReferenceAndIndexResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("blocks")
            .push(&request.path.block_ref.to_string())
            .push("events")
            .push(&request.path.event_index.to_string());
        let response = self.client.get(url).query(&request.query).send().await?;
        Ok(EventsByBlockReferenceAndIndexRequest::parse_response(response).await?)
    }
    ///Get block extrinsics
    ///
    ///If a hash is passed, returns the extrinsics for the matching block. If a number is passed, gives the extrinsis for the block by that number - could be multiple blocks if there's a pruned block in that slot.
    ///
    ///GET /blocks/{block_ref}/extrinsics
    pub async fn extrinsics_by_block_reference(
        &self,
        request: ExtrinsicsByBlockReferenceRequest,
    ) -> anyhow::Result<ExtrinsicsByBlockReferenceResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("blocks")
            .push(&request.path.block_ref.to_string())
            .push("extrinsics");
        let response = self.client.get(url).query(&request.query).send().await?;
        Ok(ExtrinsicsByBlockReferenceRequest::parse_response(response).await?)
    }
    ///Get block extrinsics by index
    ///
    ///Returns the extrinsics in the given block at the given index. It can return multiple extrinsics if a number is passed and there's a pruned block in that slot.
    ///
    ///GET /blocks/{block_ref}/extrinsics/{extrinsic_index}
    pub async fn extrinsics_by_block_reference_and_index(
        &self,
        request: ExtrinsicsByBlockReferenceAndIndexRequest,
    ) -> anyhow::Result<ExtrinsicsByBlockReferenceAndIndexResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("blocks")
            .push(&request.path.block_ref.to_string())
            .push("extrinsics")
            .push(&request.path.extrinsic_index.to_string());
        let response = self.client.get(url).send().await?;
        Ok(ExtrinsicsByBlockReferenceAndIndexRequest::parse_response(response).await?)
    }
    ///Get block extrinsic calls
    ///
    ///Returns the calls for extrinsic in a block by block reference and 0-based extrinsic index.
    ///
    ///GET /blocks/{block_ref}/extrinsics/{extrinsic_index}/calls
    pub async fn calls_by_block_reference_and_extrinsic_index(
        &self,
        request: CallsByBlockReferenceAndExtrinsicIndexRequest,
    ) -> anyhow::Result<SubCallsByHashResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("blocks")
            .push(&request.path.block_ref.to_string())
            .push("extrinsics")
            .push(&request.path.extrinsic_index.to_string())
            .push("calls");
        let response = self.client.get(url).query(&request.query).send().await?;
        Ok(
            CallsByBlockReferenceAndExtrinsicIndexRequest::parse_response(response)
                .await?,
        )
    }
    ///Get block extrinsic events
    ///
    ///Returns the events for extrinsic in a block by block reference and 0-based extrinsic index.
    ///
    ///GET /blocks/{block_ref}/extrinsics/{extrinsic_index}/events
    pub async fn events_by_block_reference_and_extrinsic_index(
        &self,
        request: EventsByBlockReferenceAndExtrinsicIndexRequest,
    ) -> anyhow::Result<EventsByExtrinsicHashResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("blocks")
            .push(&request.path.block_ref.to_string())
            .push("extrinsics")
            .push(&request.path.extrinsic_index.to_string())
            .push("events");
        let response = self.client.get(url).query(&request.query).send().await?;
        Ok(
            EventsByBlockReferenceAndExtrinsicIndexRequest::parse_response(response)
                .await?,
        )
    }
    ///Get block traces
    ///
    ///If a hash is passed, returns the traces for the matching block. If a number is passed, returns the traces for the blocks with that number - could be multiple blocks if there's a pruned block in that slot.
    ///
    ///GET /blocks/{block_ref}/traces
    pub async fn traces_by_block_reference(
        &self,
        request: TracesByBlockReferenceRequest,
    ) -> anyhow::Result<TracesByBlockReferenceResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("blocks")
            .push(&request.path.block_ref.to_string())
            .push("traces");
        let response = self.client.get(url).query(&request.query).send().await?;
        Ok(TracesByBlockReferenceRequest::parse_response(response).await?)
    }
    ///Get calls
    ///
    ///Returns all calls from the database that satisfy the query parameters. It will return a paginated response, ordered descending by block number, then call id.
    ///
    ///GET /calls
    pub async fn calls(&self, request: CallsRequest) -> anyhow::Result<CallsResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("calls");
        let response = self.client.get(url).query(&request.query).send().await?;
        Ok(CallsRequest::parse_response(response).await?)
    }
    ///Get call by hash
    ///
    ///Returns the call by its hash.
    ///
    ///GET /calls/{call_hash}
    pub async fn call_by_hash(
        &self,
        request: CallByHashRequest,
    ) -> anyhow::Result<CallByHashResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("calls")
            .push(&request.path.call_hash.to_string());
        let response = self.client.get(url).query(&request.query).send().await?;
        Ok(CallByHashRequest::parse_response(response).await?)
    }
    ///Get call arguments
    ///
    ///Returns the arguments of a runtime call by its hash.
    ///
    ///GET /calls/{call_hash}/args
    pub async fn call_args_by_hash(
        &self,
        request: CallArgsByHashRequest,
    ) -> anyhow::Result<CallArgsByHashResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("calls")
            .push(&request.path.call_hash.to_string())
            .push("args");
        let response = self.client.get(url).send().await?;
        Ok(CallArgsByHashRequest::parse_response(response).await?)
    }
    ///Get call extrinsic
    ///
    ///Returns the extrinsic of a call by call hash.
    ///
    ///GET /calls/{call_hash}/extrinsic
    pub async fn call_extrinsic_by_hash(
        &self,
        request: CallExtrinsicByHashRequest,
    ) -> anyhow::Result<ExtrinsicByHashResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("calls")
            .push(&request.path.call_hash.to_string())
            .push("extrinsic");
        let response = self.client.get(url).send().await?;
        Ok(CallExtrinsicByHashRequest::parse_response(response).await?)
    }
    ///Get parent call
    ///
    ///Returns a parent call by the sub call's hash.
    ///
    ///GET /calls/{call_hash}/parent
    pub async fn parent_call_by_hash(
        &self,
        request: ParentCallByHashRequest,
    ) -> anyhow::Result<CallByHashResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("calls")
            .push(&request.path.call_hash.to_string())
            .push("parent");
        let response = self.client.get(url).query(&request.query).send().await?;
        Ok(ParentCallByHashRequest::parse_response(response).await?)
    }
    ///Get sub calls
    ///
    ///Returns sub calls call by a parent call's hash.
    ///
    ///GET /calls/{call_hash}/subs
    pub async fn sub_calls_by_hash(
        &self,
        request: SubCallsByHashRequest,
    ) -> anyhow::Result<SubCallsByHashResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("calls")
            .push(&request.path.call_hash.to_string())
            .push("subs");
        let response = self.client.get(url).query(&request.query).send().await?;
        Ok(SubCallsByHashRequest::parse_response(response).await?)
    }
    ///Get events
    ///
    ///Returns all events from the database that satisfy the query parameters. It will return a paginated response, ordered descending by block number and ascending event index.
    ///
    ///GET /events
    pub async fn events(
        &self,
        request: EventsRequest,
    ) -> anyhow::Result<EventsResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("events");
        let response = self.client.get(url).query(&request.query).send().await?;
        Ok(EventsRequest::parse_response(response).await?)
    }
    ///Get event by hash
    ///
    ///Returns the event by its hash.
    ///
    ///GET /events/{event_hash}
    pub async fn event_by_hash(
        &self,
        request: EventByHashRequest,
    ) -> anyhow::Result<EventByHashResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("events")
            .push(&request.path.event_hash.to_string());
        let response = self.client.get(url).query(&request.query).send().await?;
        Ok(EventByHashRequest::parse_response(response).await?)
    }
    ///Get event arguments
    ///
    ///Returns the arguments of a runtime call by its hash.
    ///
    ///GET /events/{event_hash}/args
    pub async fn event_args_by_hash(
        &self,
        request: EventArgsByHashRequest,
    ) -> anyhow::Result<EventArgsByHashResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("events")
            .push(&request.path.event_hash.to_string())
            .push("args");
        let response = self.client.get(url).send().await?;
        Ok(EventArgsByHashRequest::parse_response(response).await?)
    }
    ///Get extrinsics
    ///
    ///Returns all extrinsics from the database that satisfy the query parameters. It will return a paginated response, ordered descending by block number and ascending extrinsic index.
    ///
    ///GET /extrinsics
    pub async fn extrinsics(
        &self,
        request: ExtrinsicsRequest,
    ) -> anyhow::Result<ExtrinsicsResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("extrinsics");
        let response = self.client.get(url).query(&request.query).send().await?;
        Ok(ExtrinsicsRequest::parse_response(response).await?)
    }
    ///Get extrinsic by hash
    ///
    ///Returns the extrinsic by its hash.
    ///
    ///GET /extrinsics/{extrinsic_hash}
    pub async fn extrinsic_by_hash(
        &self,
        request: ExtrinsicByHashRequest,
    ) -> anyhow::Result<ExtrinsicByHashResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("extrinsics")
            .push(&request.path.extrinsic_hash.to_string());
        let response = self.client.get(url).send().await?;
        Ok(ExtrinsicByHashRequest::parse_response(response).await?)
    }
    ///Get extrinsic root call
    ///
    ///Returns the root call of an extrinsic by its hash.
    ///
    ///GET /extrinsics/{extrinsic_hash}/call
    pub async fn extrinsic_root_call_by_hash(
        &self,
        request: ExtrinsicRootCallByHashRequest,
    ) -> anyhow::Result<CallByHashResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("extrinsics")
            .push(&request.path.extrinsic_hash.to_string())
            .push("call");
        let response = self.client.get(url).query(&request.query).send().await?;
        Ok(ExtrinsicRootCallByHashRequest::parse_response(response).await?)
    }
    ///Get extrinsic calls
    ///
    ///Returns the calls in an extrinsic by extrinsic hash.
    ///
    ///GET /extrinsics/{extrinsic_hash}/calls
    pub async fn calls_by_extrinsic_hash(
        &self,
        request: CallsByExtrinsicHashRequest,
    ) -> anyhow::Result<SubCallsByHashResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("extrinsics")
            .push(&request.path.extrinsic_hash.to_string())
            .push("calls");
        let response = self.client.get(url).query(&request.query).send().await?;
        Ok(CallsByExtrinsicHashRequest::parse_response(response).await?)
    }
    ///Get extrinsic events
    ///
    ///Returns the events in an extrinsic by extrinsic hash.
    ///
    ///GET /extrinsics/{extrinsic_hash}/events
    pub async fn events_by_extrinsic_hash(
        &self,
        request: EventsByExtrinsicHashRequest,
    ) -> anyhow::Result<EventsByExtrinsicHashResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("extrinsics")
            .push(&request.path.extrinsic_hash.to_string())
            .push("events");
        let response = self.client.get(url).query(&request.query).send().await?;
        Ok(EventsByExtrinsicHashRequest::parse_response(response).await?)
    }
    ///Get genesis records
    ///
    ///Returns a paginated list of all genesis storage records.
    ///
    ///GET /genesis
    pub async fn genesis_records(
        &self,
        request: GenesisRecordsRequest,
    ) -> anyhow::Result<GenesisRecordsResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("genesis");
        let response = self.client.get(url).query(&request.query).send().await?;
        Ok(GenesisRecordsRequest::parse_response(response).await?)
    }
    ///Get metadata list
    ///
    ///Returns a list of metadata summaries for all runtime versions.
    ///
    ///GET /metadata
    pub async fn metadata_list(
        &self,
        request: MetadataListRequest,
    ) -> anyhow::Result<MetadataListResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("metadata");
        let response = self.client.get(url).query(&request.query).send().await?;
        Ok(MetadataListRequest::parse_response(response).await?)
    }
    ///Get metadata by spec version
    ///
    ///Returns the metadata by its spec version.
    ///
    ///GET /metadata/{spec_version}
    pub async fn metadata(
        &self,
        request: MetadataRequest,
    ) -> anyhow::Result<MetadataResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("metadata")
            .push(&request.path.spec_version.to_string());
        let response = self.client.get(url).send().await?;
        Ok(MetadataRequest::parse_response(response).await?)
    }
    ///Get metadata hex
    ///
    ///Returns the SCALE-encoded hexadecimal string for the prefixed metadata.
    ///
    ///GET /metadata/{spec_version}/hex
    pub async fn metadata_hex(
        &self,
        request: MetadataHexRequest,
    ) -> anyhow::Result<MetadataHexResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("metadata")
            .push(&request.path.spec_version.to_string())
            .push("hex");
        let response = self.client.get(url).send().await?;
        Ok(MetadataHexRequest::parse_response(response).await?)
    }
    ///Get metadata JSON
    ///
    ///Returns the original Substrate runtime metadata by its spec version in JSON representation.
    ///
    ///GET /metadata/{spec_version}/json
    pub async fn metadata_json(
        &self,
        request: MetadataJsonRequest,
    ) -> anyhow::Result<MetadataJsonResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("metadata")
            .push(&request.path.spec_version.to_string())
            .push("json");
        let response = self.client.get(url).send().await?;
        Ok(MetadataJsonRequest::parse_response(response).await?)
    }
    ///Get metadata pallets
    ///
    ///Returns pallets in a metadata version.
    ///
    ///GET /metadata/{spec_version}/pallets
    pub async fn metadata_pallets(
        &self,
        request: MetadataPalletsRequest,
    ) -> anyhow::Result<MetadataPalletsResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("metadata")
            .push(&request.path.spec_version.to_string())
            .push("pallets");
        let response = self.client.get(url).send().await?;
        Ok(MetadataPalletsRequest::parse_response(response).await?)
    }
    ///Get metadata pallet
    ///
    ///Returns the full metadata pallet by metadata spec version and pallet index.
    ///
    ///GET /metadata/{spec_version}/pallets/{pallet_index}
    pub async fn metadata_pallet(
        &self,
        request: MetadataPalletRequest,
    ) -> anyhow::Result<MetadataPalletResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("metadata")
            .push(&request.path.spec_version.to_string())
            .push("pallets")
            .push(&request.path.pallet_index.to_string());
        let response = self.client.get(url).send().await?;
        Ok(MetadataPalletRequest::parse_response(response).await?)
    }
    ///Get metadata pallet calls
    ///
    ///Returns the calls in a pallet in a metadata version.
    ///
    ///GET /metadata/{spec_version}/pallets/{pallet_index}/calls
    pub async fn metadata_pallet_calls(
        &self,
        request: MetadataPalletCallsRequest,
    ) -> anyhow::Result<MetadataPalletCallsResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("metadata")
            .push(&request.path.spec_version.to_string())
            .push("pallets")
            .push(&request.path.pallet_index.to_string())
            .push("calls");
        let response = self.client.get(url).send().await?;
        Ok(MetadataPalletCallsRequest::parse_response(response).await?)
    }
    ///Get metadata pallet constants
    ///
    ///Returns the constants in a pallet in a metadata version.
    ///
    ///GET /metadata/{spec_version}/pallets/{pallet_index}/constants
    pub async fn metadata_pallet_constants(
        &self,
        request: MetadataPalletConstantsRequest,
    ) -> anyhow::Result<MetadataPalletConstantsResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("metadata")
            .push(&request.path.spec_version.to_string())
            .push("pallets")
            .push(&request.path.pallet_index.to_string())
            .push("constants");
        let response = self.client.get(url).send().await?;
        Ok(MetadataPalletConstantsRequest::parse_response(response).await?)
    }
    ///Get metadata pallet errors
    ///
    ///Returns the errors in a pallet in a metadata version.
    ///
    ///GET /metadata/{spec_version}/pallets/{pallet_index}/errors
    pub async fn metadata_pallet_errors(
        &self,
        request: MetadataPalletErrorsRequest,
    ) -> anyhow::Result<MetadataPalletErrorsResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("metadata")
            .push(&request.path.spec_version.to_string())
            .push("pallets")
            .push(&request.path.pallet_index.to_string())
            .push("errors");
        let response = self.client.get(url).send().await?;
        Ok(MetadataPalletErrorsRequest::parse_response(response).await?)
    }
    ///Get metadata pallet events
    ///
    ///Returns the events in a pallet in a metadata version.
    ///
    ///GET /metadata/{spec_version}/pallets/{pallet_index}/events
    pub async fn metadata_pallet_events(
        &self,
        request: MetadataPalletEventsRequest,
    ) -> anyhow::Result<MetadataPalletEventsResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("metadata")
            .push(&request.path.spec_version.to_string())
            .push("pallets")
            .push(&request.path.pallet_index.to_string())
            .push("events");
        let response = self.client.get(url).send().await?;
        Ok(MetadataPalletEventsRequest::parse_response(response).await?)
    }
    ///Get metadata pallet storage items
    ///
    ///Returns the storage items in a pallet in a metadata version.
    ///
    ///GET /metadata/{spec_version}/pallets/{pallet_index}/storage
    pub async fn metadata_pallet_storage_items(
        &self,
        request: MetadataPalletStorageItemsRequest,
    ) -> anyhow::Result<MetadataPalletStorageItemsResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("metadata")
            .push(&request.path.spec_version.to_string())
            .push("pallets")
            .push(&request.path.pallet_index.to_string())
            .push("storage");
        let response = self.client.get(url).send().await?;
        Ok(MetadataPalletStorageItemsRequest::parse_response(response).await?)
    }
    ///Get traces
    ///
    ///Returns all traces from the database that satisfy the query parameters. It will return a paginated response, ordered descending by block number, then ascending trace index.
    ///
    ///GET /traces
    pub async fn traces(
        &self,
        request: TracesRequest,
    ) -> anyhow::Result<TracesResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("traces");
        let response = self.client.get(url).query(&request.query).send().await?;
        Ok(TracesRequest::parse_response(response).await?)
    }
    ///Get trace by hash
    ///
    ///Returns the trace by its hash.
    ///
    ///GET /traces/{trace_hash}
    pub async fn trace_by_hash(
        &self,
        request: TraceByHashRequest,
    ) -> anyhow::Result<TraceByHashResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("traces")
            .push(&request.path.trace_hash.to_string());
        let response = self.client.get(url).send().await?;
        Ok(TraceByHashRequest::parse_response(response).await?)
    }
    ///Get trace value
    ///
    ///Returns the value of a trace record by its hash.
    ///
    ///GET /traces/{trace_hash}/value
    pub async fn trace_value_by_hash(
        &self,
        request: TraceValueByHashRequest,
    ) -> anyhow::Result<TraceValueByHashResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("traces")
            .push(&request.path.trace_hash.to_string())
            .push("value");
        let response = self.client.get(url).send().await?;
        Ok(TraceValueByHashRequest::parse_response(response).await?)
    }
}

