#![allow(clippy::default_trait_access)]
#![allow(clippy::doc_markdown)]
#![allow(clippy::enum_variant_names)]
#![allow(clippy::large_enum_variant)]
#![allow(clippy::missing_panics_doc)]
#![allow(clippy::result_large_err)]
#![allow(clippy::struct_field_names)]
#![allow(clippy::too_many_lines)]
#![allow(clippy::unnecessary_wraps)]
#![allow(clippy::unused_self)]
#![allow(dead_code)]

//!
//! AUTO-GENERATED CODE - DO NOT EDIT!
//!
//! Submerge Crystal API v1
//! Source: /Users/arjunporwal/Documents/Helikon/submerge/submerge-crystal/api-spec/submerge-crystal-api.json
//! Version: 1.0.0
//! Generated by `oas3-gen v0.23.5`
//!
//! REST API for Submerge Crystal, the core indexer component of Submerge.
//! 
//! Submerge API endpoints are grouped under five resource sets:
//! - Blocks
//! - Calls
//! - Events
//! - Extrinsics
//! - Genesis
//! - Metadata
//! - Traces
//! 
//! Public API is limited by 5 requests per second.
//! Request query parameters use `snake_case`; response fields use `camelCase`.

mod types;
mod client;
pub use types::*;
pub use client::SubmergeCrystalApiV1Client;

