[package]
name = "submerge-metrics"
version = "0.0.1"
rust-version = "1.83.0"
edition = "2021"
authors = ["kukabi <kutsal@helikon.io>"]

[dependencies]
log = { workspace = true }
once_cell = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
prometheus = { workspace = true }
warp = { workspace = true }